#!/bin/bash
b=(石头 剪刀 布)
a=$[RANDOM%3]
tmp=${b[$a]}
while :
do
read -p "请出拳:" c
if [ $tmp == 石头];then
   if [ $c == 石头 ];then
      echo "平局"
   elif [ $c == 剪刀 ];then
      echo "你输了"
   elif [ $c == 布 ];then
      echo "你赢了"
       exit
   else
      echo "按规矩来"
  fi
fi
if [ $tmp == 剪刀 ];then
   if [ $c == 石头 ];then
      echo "你赢了"
      exit
         elif [ $c == 剪刀 ];then
      echo "平局"
   elif [ $c == 布 ];then
      echo "你输了"
   else
      echo "按规矩来"
  fi
fi
if [ $tmp == 布 ];then
   if [ $c == 石头 ];then
      echo "你输了"
   elif [ $c == 剪刀 ];then
      echo "你赢了"
      exit
   elif [ $c == 布 ];then
      echo "平局"
   else
      echo "按规矩来"
  fi
fi
done

